# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U77lEu74_iA-YEBi00PSnZpjDiazmVRu
"""

str="hello world i am shifa  arshad khan"
#str.endswith("fa")
#str.capitalize()
#str.replace("s","S")
#str.find("a")
str.count("a")

name=input("enter users name:")
print(len(name))

str="hello$world$its$meshifa$khan"
str.count("$")

age=33
if(age>=18):
  print("eligible for license")
else:
  print("not eligible for license")

marks=88
if (marks>=90):
  print("grade a")
elif(90>=marks>=80):
  print("grade b")
elif(80>=marks>=70):
  print("grade c")
else:
  print('grade d')

number=77
if(number%7==0):
  print("multiple of seven")
else:
  print("not multiple of seven")

list=[1,5,3,7,2,9]
print("smallest",min(list))
print("largest",max(list))

word=input("enter the word")
if(word==word[::-1]):
  print("palindrone")
else:
  print("not palindrone")

import random
n=random.randint(1,10)
while True:
  g=int(input("enter the number"))
  if g==n:
    print("correct")
  else:
    print("wrong")

